spring:
  webflux:
    base-path: /reactive-calendar
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB}?authSource=admin

springdoc:
  swagger-ui:
    path: /api-doc.html